### PR TITLE
allow parsing text panel contents into reports

### PR DESCRIPTION
**Pull request by Capitrium**
Adds functionality to parse contents of text panels so that users can include written summaries, etc. in generated reports.

### CODE REVIEW

**Comment by IzakMarais** [comment]
Nice feature with regression tests added! Thanks. 

I'm just not sure about making this the default behaviour. Text panels can also contain markdown or html possibly with images (see #63). I don't expect that this feature will play nicely with those use cases.

And if it isn't the default behaviour, making it configurable adds more complexity.

Also thanks for fixing the typos.

**Comment by Capitrium** [comment]
Agreed that this probably shouldn't be the default behaviour; I'd actually run into that grafana bug you linked while developing the dashboard that uses this feature, so I'm glad that's being worked on!

I think your suggestion is probably the easiest way to make this configurable - adding something like an `extractText` query parameter that toggles the feature and custom latex template.

**Comment by Capitrium** [comment]
I'm going to close this out as I don't have time to work on the proposed changes; we ended up going a different way, modifying the reporter to pull images from Grafana and text sections from a database to compile our custom reports.

**Comment by IzakMarais** [comment]
OK, thanks for the feedback.

**Pull request closed without merging**
