### PR TITLE
add cmd_template flag to support custom template in command line mode

### PR DESCRIPTION
**Pull request by bolsunovskyi**

### CODE REVIEW

**Comment by IzakMarais** [comment]
Excellent, thanks! I'll try to merge this ASAP.

**Comment by bolsunovskyi** [comment]
You welcome, please check work of this flag locally.

**Comment by IzakMarais** [comment]
> You welcome, please check work of this flag locally.

I checked it and can confirm that it works as expected.

**Comment by IzakMarais** [comment]
This closes #143.

**Pull request merged**
