### PR TITLE
Multilevel Variable Management.

### PR DESCRIPTION
**Pull request by JCN-9000**
This is a manual merge of PR #22 , since I needed that functionality.
I've added the capability of expanding Grafana variables found in Title of Panels and Rows.
Feel free to grab the useful stuff and discard the rest.

### CODE REVIEW

**Comment by n3k232** [comment]
does this one allow me to use variables with multivalues like:
var-hostname=host1&var-hostname=host2?

**Comment by IzakMarais** [comment]
@n3k232 No not yet. I am busy implementing that now. Will merge it into master shortly.

**Comment by n3k232** [comment]
@IzakMarais that would be Great! =)

**Comment by IzakMarais** [comment]
Thanks, I did a manual merge of #22 myself. It is now in master with improvements to variable handling.

**Pull request closed without merging**
