### PR TITLE
Add proto option to allow https access to grafana

### PR DESCRIPTION
**Pull request by ArcticSnowman**
Add proto option to allow https access to grafana

### CODE REVIEW

**Comment by IzakMarais** [comment]
Maybe I don't understand the issue completely, but does this change solve your problem? Is there not authentication that has to happen in addition to changing the protocol from http to https? 

Or are you using https without basic user auth? I still plan on merging https://github.com/IzakMarais/reporter/pull/3 when I have the time. That contains a solution for the auth part.

**Comment by IzakMarais** [comment]
Btw. thanks for the PR :).

**Comment by ArcticSnowman** [comment]
To make full use of this you do need the authentication PR..  #3   
However the PR should best be split into one for the authentication and one for template.

**Comment by IzakMarais** [comment]
OK thanks for the clarification. I will try to get round to merging them both shortly.

**Pull request merged**
